// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pulsewatch-backend/internal/models"
	store "pulsewatch-backend/internal/store"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMonitorRepository is a mock of MonitorRepository interface.
type MockMonitorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorRepositoryMockRecorder
	isgomock struct{}
}

// MockMonitorRepositoryMockRecorder is the mock recorder for MockMonitorRepository.
type MockMonitorRepositoryMockRecorder struct {
	mock *MockMonitorRepository
}

// NewMockMonitorRepository creates a new mock instance.
func NewMockMonitorRepository(ctrl *gomock.Controller) *MockMonitorRepository {
	mock := &MockMonitorRepository{ctrl: ctrl}
	mock.recorder = &MockMonitorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorRepository) EXPECT() *MockMonitorRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockMonitorRepository) Count(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockMonitorRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockMonitorRepository)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockMonitorRepository) Create(ctx context.Context, in models.CreateMonitorInput) (models.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(models.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMonitorRepositoryMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMonitorRepository)(nil).Create), ctx, in)
}

// Delete mocks base method.
func (m *MockMonitorRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMonitorRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMonitorRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockMonitorRepository) GetByID(ctx context.Context, id string) (models.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMonitorRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMonitorRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockMonitorRepository) List(ctx context.Context) ([]models.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMonitorRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMonitorRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockMonitorRepository) Update(ctx context.Context, id string, in models.UpdateMonitorInput) (models.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, in)
	ret0, _ := ret[0].(models.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMonitorRepositoryMockRecorder) Update(ctx, id, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMonitorRepository)(nil).Update), ctx, id, in)
}

// MockIncidentRepository is a mock of IncidentRepository interface.
type MockIncidentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentRepositoryMockRecorder
	isgomock struct{}
}

// MockIncidentRepositoryMockRecorder is the mock recorder for MockIncidentRepository.
type MockIncidentRepositoryMockRecorder struct {
	mock *MockIncidentRepository
}

// NewMockIncidentRepository creates a new mock instance.
func NewMockIncidentRepository(ctrl *gomock.Controller) *MockIncidentRepository {
	mock := &MockIncidentRepository{ctrl: ctrl}
	mock.recorder = &MockIncidentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentRepository) EXPECT() *MockIncidentRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockIncidentRepository) List(ctx context.Context, monitorID string, limit, offset int) ([]models.Incident, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, monitorID, limit, offset)
	ret0, _ := ret[0].([]models.Incident)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIncidentRepositoryMockRecorder) List(ctx, monitorID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIncidentRepository)(nil).List), ctx, monitorID, limit, offset)
}

// MockAlertSettingsRepository is a mock of AlertSettingsRepository interface.
type MockAlertSettingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAlertSettingsRepositoryMockRecorder
	isgomock struct{}
}

// MockAlertSettingsRepositoryMockRecorder is the mock recorder for MockAlertSettingsRepository.
type MockAlertSettingsRepositoryMockRecorder struct {
	mock *MockAlertSettingsRepository
}

// NewMockAlertSettingsRepository creates a new mock instance.
func NewMockAlertSettingsRepository(ctrl *gomock.Controller) *MockAlertSettingsRepository {
	mock := &MockAlertSettingsRepository{ctrl: ctrl}
	mock.recorder = &MockAlertSettingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertSettingsRepository) EXPECT() *MockAlertSettingsRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAlertSettingsRepository) Get(ctx context.Context) (models.AlertSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(models.AlertSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAlertSettingsRepositoryMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAlertSettingsRepository)(nil).Get), ctx)
}

// Update mocks base method.
func (m *MockAlertSettingsRepository) Update(ctx context.Context, in models.UpdateAlertSettingsInput) (models.AlertSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(models.AlertSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAlertSettingsRepositoryMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlertSettingsRepository)(nil).Update), ctx, in)
}

// MockCheckResultRepository is a mock of CheckResultRepository interface.
type MockCheckResultRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheckResultRepositoryMockRecorder
	isgomock struct{}
}

// MockCheckResultRepositoryMockRecorder is the mock recorder for MockCheckResultRepository.
type MockCheckResultRepositoryMockRecorder struct {
	mock *MockCheckResultRepository
}

// NewMockCheckResultRepository creates a new mock instance.
func NewMockCheckResultRepository(ctrl *gomock.Controller) *MockCheckResultRepository {
	mock := &MockCheckResultRepository{ctrl: ctrl}
	mock.recorder = &MockCheckResultRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckResultRepository) EXPECT() *MockCheckResultRepositoryMockRecorder {
	return m.recorder
}

// History mocks base method.
func (m *MockCheckResultRepository) History(ctx context.Context, monitorID string, since time.Time, bucketWidth time.Duration) ([]store.HistoryBucket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", ctx, monitorID, since, bucketWidth)
	ret0, _ := ret[0].([]store.HistoryBucket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockCheckResultRepositoryMockRecorder) History(ctx, monitorID, since, bucketWidth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockCheckResultRepository)(nil).History), ctx, monitorID, since, bucketWidth)
}

// UptimePercentage mocks base method.
func (m *MockCheckResultRepository) UptimePercentage(ctx context.Context, monitorID string, since time.Time) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UptimePercentage", ctx, monitorID, since)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UptimePercentage indicates an expected call of UptimePercentage.
func (mr *MockCheckResultRepositoryMockRecorder) UptimePercentage(ctx, monitorID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UptimePercentage", reflect.TypeOf((*MockCheckResultRepository)(nil).UptimePercentage), ctx, monitorID, since)
}
