// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pulsewatch-backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMonitorLister is a mock of MonitorLister interface.
type MockMonitorLister struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorListerMockRecorder
	isgomock struct{}
}

// MockMonitorListerMockRecorder is the mock recorder for MockMonitorLister.
type MockMonitorListerMockRecorder struct {
	mock *MockMonitorLister
}

// NewMockMonitorLister creates a new mock instance.
func NewMockMonitorLister(ctrl *gomock.Controller) *MockMonitorLister {
	mock := &MockMonitorLister{ctrl: ctrl}
	mock.recorder = &MockMonitorListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorLister) EXPECT() *MockMonitorListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockMonitorLister) List(ctx context.Context) ([]models.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMonitorListerMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMonitorLister)(nil).List), ctx)
}
