// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	alert "pulsewatch-backend/internal/alert"
	models "pulsewatch-backend/internal/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMonitorLookup is a mock of MonitorLookup interface.
type MockMonitorLookup struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorLookupMockRecorder
	isgomock struct{}
}

// MockMonitorLookupMockRecorder is the mock recorder for MockMonitorLookup.
type MockMonitorLookupMockRecorder struct {
	mock *MockMonitorLookup
}

// NewMockMonitorLookup creates a new mock instance.
func NewMockMonitorLookup(ctrl *gomock.Controller) *MockMonitorLookup {
	mock := &MockMonitorLookup{ctrl: ctrl}
	mock.recorder = &MockMonitorLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorLookup) EXPECT() *MockMonitorLookupMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockMonitorLookup) GetByID(ctx context.Context, id string) (models.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMonitorLookupMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMonitorLookup)(nil).GetByID), ctx, id)
}

// MockAlertSettingsStore is a mock of AlertSettingsStore interface.
type MockAlertSettingsStore struct {
	ctrl     *gomock.Controller
	recorder *MockAlertSettingsStoreMockRecorder
	isgomock struct{}
}

// MockAlertSettingsStoreMockRecorder is the mock recorder for MockAlertSettingsStore.
type MockAlertSettingsStoreMockRecorder struct {
	mock *MockAlertSettingsStore
}

// NewMockAlertSettingsStore creates a new mock instance.
func NewMockAlertSettingsStore(ctrl *gomock.Controller) *MockAlertSettingsStore {
	mock := &MockAlertSettingsStore{ctrl: ctrl}
	mock.recorder = &MockAlertSettingsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertSettingsStore) EXPECT() *MockAlertSettingsStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAlertSettingsStore) Get(ctx context.Context) (models.AlertSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(models.AlertSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAlertSettingsStoreMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAlertSettingsStore)(nil).Get), ctx)
}

// MockIncidentStore is a mock of IncidentStore interface.
type MockIncidentStore struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentStoreMockRecorder
	isgomock struct{}
}

// MockIncidentStoreMockRecorder is the mock recorder for MockIncidentStore.
type MockIncidentStoreMockRecorder struct {
	mock *MockIncidentStore
}

// NewMockIncidentStore creates a new mock instance.
func NewMockIncidentStore(ctrl *gomock.Controller) *MockIncidentStore {
	mock := &MockIncidentStore{ctrl: ctrl}
	mock.recorder = &MockIncidentStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentStore) EXPECT() *MockIncidentStoreMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockIncidentStore) Open(ctx context.Context, monitorID string, startedAt time.Time, cause string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, monitorID, startedAt, cause)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockIncidentStoreMockRecorder) Open(ctx, monitorID, startedAt, cause any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockIncidentStore)(nil).Open), ctx, monitorID, startedAt, cause)
}

// OpenIncidents mocks base method.
func (m *MockIncidentStore) OpenIncidents(ctx context.Context) ([]models.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenIncidents", ctx)
	ret0, _ := ret[0].([]models.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenIncidents indicates an expected call of OpenIncidents.
func (mr *MockIncidentStoreMockRecorder) OpenIncidents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenIncidents", reflect.TypeOf((*MockIncidentStore)(nil).OpenIncidents), ctx)
}

// Resolve mocks base method.
func (m *MockIncidentStore) Resolve(ctx context.Context, monitorID string, resolvedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, monitorID, resolvedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockIncidentStoreMockRecorder) Resolve(ctx, monitorID, resolvedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockIncidentStore)(nil).Resolve), ctx, monitorID, resolvedAt)
}

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
	isgomock struct{}
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockSender) Send(ctx context.Context, target string, ev alert.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, target, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSenderMockRecorder) Send(ctx, target, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSender)(nil).Send), ctx, target, ev)
}
