// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	models "pulsewatch-backend/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockcheckResultCreator is a mock of checkResultCreator interface.
type MockcheckResultCreator struct {
	ctrl     *gomock.Controller
	recorder *MockcheckResultCreatorMockRecorder
	isgomock struct{}
}

// MockcheckResultCreatorMockRecorder is the mock recorder for MockcheckResultCreator.
type MockcheckResultCreatorMockRecorder struct {
	mock *MockcheckResultCreator
}

// NewMockcheckResultCreator creates a new mock instance.
func NewMockcheckResultCreator(ctrl *gomock.Controller) *MockcheckResultCreator {
	mock := &MockcheckResultCreator{ctrl: ctrl}
	mock.recorder = &MockcheckResultCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcheckResultCreator) EXPECT() *MockcheckResultCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockcheckResultCreator) Create(ctx context.Context, result models.CheckResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockcheckResultCreatorMockRecorder) Create(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockcheckResultCreator)(nil).Create), ctx, result)
}

// Mockbroadcaster is a mock of broadcaster interface.
type Mockbroadcaster struct {
	ctrl     *gomock.Controller
	recorder *MockbroadcasterMockRecorder
	isgomock struct{}
}

// MockbroadcasterMockRecorder is the mock recorder for Mockbroadcaster.
type MockbroadcasterMockRecorder struct {
	mock *Mockbroadcaster
}

// NewMockbroadcaster creates a new mock instance.
func NewMockbroadcaster(ctrl *gomock.Controller) *Mockbroadcaster {
	mock := &Mockbroadcaster{ctrl: ctrl}
	mock.recorder = &MockbroadcasterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockbroadcaster) EXPECT() *MockbroadcasterMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *Mockbroadcaster) Broadcast(v any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", v)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockbroadcasterMockRecorder) Broadcast(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*Mockbroadcaster)(nil).Broadcast), v)
}

// MockresultDispatcher is a mock of resultDispatcher interface.
type MockresultDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockresultDispatcherMockRecorder
	isgomock struct{}
}

// MockresultDispatcherMockRecorder is the mock recorder for MockresultDispatcher.
type MockresultDispatcherMockRecorder struct {
	mock *MockresultDispatcher
}

// NewMockresultDispatcher creates a new mock instance.
func NewMockresultDispatcher(ctrl *gomock.Controller) *MockresultDispatcher {
	mock := &MockresultDispatcher{ctrl: ctrl}
	mock.recorder = &MockresultDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresultDispatcher) EXPECT() *MockresultDispatcherMockRecorder {
	return m.recorder
}

// HandleResult mocks base method.
func (m *MockresultDispatcher) HandleResult(ctx context.Context, r models.CheckResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleResult", ctx, r)
}

// HandleResult indicates an expected call of HandleResult.
func (mr *MockresultDispatcherMockRecorder) HandleResult(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleResult", reflect.TypeOf((*MockresultDispatcher)(nil).HandleResult), ctx, r)
}
